### ISSUE TITLE
Include APF/AAPF meet: 2012 Viking Challenge, December 8, 2012, Solvang CA

### ISSUE THREAD

**Issue by ahstram** [sstangl/openpowerlifting#1091]
Results are here: http://worldpowerliftingcongress.com/wp-content/uploads/results/archive/Resutls%20120812%20CA%20Meet.htm

Lifters under the "Lifters Who Competed AAPF" section were in the drug-tested (AAPF) pool of the meet.

**Comment by sstangl** [comment]
Added, thank you! Note that we don't currently have a way to show AAPF lifters in our "Tested" selector, but we'll gain that ability soon, and they've been tagged as such in the data.
