### ISSUE TITLE
Import Czech IPF results

### ISSUE THREAD

**Issue by photon-rain** [sstangl/openpowerlifting#1093]
The Czech IPF affiliate has nicely formatted data which can probably be auto-imported:

Pre 2018:
http://powerlifting.cuscz.cz/vysledky/souteze.htm

2018:
http://www.powerlifting-csst.cz/cz/vysledky-2018.html

Their abbreviation seems to be CSST.

**Comment by sstangl** [comment]
I am particularly excited about this.

**Comment by photon-rain** [comment]
I didn't notice earlier, but there seem to be complete nationals results back until 1994 - so heaps of meets! Although the formatting is all over the place for pre 2007.
