### ISSUE TITLE
Lifter Request: Add GPC meet

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#1192]
Lifter Carl Thompson @carl.thompson on instagram has requested that we add his missing GPC meet linked here. http://www.neilside.co.uk/index.php?showcomp=491 He could not find the results anywhere besides neilside, I know that is not preferable

**Comment by JoWhiteley** [comment]
Unfortunately, Neil is now the record keeper for GPC in the UK and Neilside is the official source of their results.  I am currently negotiating gently for these.

**Comment by JoWhiteley** [comment]
Neil gave permission!  #1202 closes this issue.  @TrystanOakley can you let Carl know.  Thanks

**Comment by JoWhiteley** [comment]
@sstangl this can close
