### ISSUE TITLE
Lifters page needs kg/lbs selection.

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#12]
The lifters.html page currently always shows results in pounds. It should be the same as chosen on index.html, and perhaps also have a selector.

To preserve that information across page loads, probably some form of localstorage is necessary.

**Comment by KDercksen** [comment]
[This might be interesting?](http://www.w3schools.com/html/html5_webstorage.asp)

**Comment by sstangl** [comment]
This was fixed by 878d4b4bcfd57aeaf12d37ec95987a9416958607.
