### ISSUE TITLE
Non-ASCII characters trying to write to ASCII stdout

### ISSUE THREAD

**Issue by DennisArnold96** [sstangl/openpowerlifting#1204]
While building the project, csvtojs.py reads the csv and builds the js array. 
The result is written to stdout.
Stdout itself seems to be ASCII-only in my case; if there was a non-ASCII character like \xed to be written, the script crashes.

**Comment by sstangl** [comment]
Is it possible to use a terminal that supports UTF-8? The whole project uses UTF-8.

That said, if `csvtojs.py` is the failure point, that means the data already built for you -- `make check && make csvfile` is enough, there's no need to build the static website also.

**Comment by DennisArnold96** [comment]
I used the "native" Terminal via SSH, that might have benn the problem
