### ISSUE TITLE
Add Iron Annihilation CFP meet 28 April 2018

### ISSUE THREAD

**Issue by FreddlesFit** [sstangl/openpowerlifting#1207]
Please be advised that this meet coefficient was calculated with Glossbrenner, NOT WILKS.

[Iron Annihilation Results.xlsx](https://github.com/sstangl/openpowerlifting/files/2005276/Iron.Annihilation.Results.xlsx)

**Comment by sstangl** [comment]
Added, thanks! Will be live on the site in a few minutes.
