### ISSUE TITLE
Add Greater London (British Powerlifting) Comps

### ISSUE THREAD

**Issue by PeteSpence** [sstangl/openpowerlifting#1219]
All results from July 2015 onwards available here:

http://www.gbpflondon.org/results

Note that there is an error in the July 2015 results. Peter Spence failed his third bench (and I am willing to provide video evidence that I did not make this attempt if such ritual humiliation is deemed necessary).

**Comment by sstangl** [comment]
Not necessary. Thank you :+1:

**Comment by sstangl** [comment]
@JoWhiteley are these meets on your radar?

**Comment by JoWhiteley** [comment]
@sstangl yeah I have have finished with the historic stuff Matt found and I am now working my way around the regional websites filling in any missing results. Pj Gentle is working her way through her region one meet per day which is really helpful. It will take some time but I will get there.
