### ISSUE TITLE
Lifter Request: Add APU Perth Open 

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#1227]
Lifter David Widjojo @davidwidjojo on instagram requested that we add this meet. The link to the results is http://ptcperth.com.au/blog/2018-apu-perth-open/

**Comment by TrystanOakley** [comment]
It is a JPEG

**Comment by sstangl** [comment]
The APU should eventually upload a PDF to their site. Could just wait for that.

**Comment by JoWhiteley** [comment]
the results are theoretically on their way.
