### ISSUE TITLE
7-year old weighing 39lbs given 573.71 Wilks points.

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#1260]
@photon-rain , it looks like we'll need some lower-bounds also. Would you be interested in looking for reasonable cutoffs on the lower end, just as you did to avoid the higher asymptote?

**Comment by sstangl** [comment]
The particular lifter was "Giacomo Ston Moritz" in HERC.

**Comment by photon-rain** [comment]
Sure thing, it seems that the IPF stops at 40kg for men and women, which seems like a reasonable place to cut it.
