### ISSUE TITLE
Richard Hulick name and meet correction

### ISSUE THREAD

**Issue by bobfredc3q** [sstangl/openpowerlifting#1268]
Richard Hulick's name was incorrectly listed as Richaed Hulick for the UPA OSIG Spring Classic on 4/28/18. It is most likely because it was also incorrectly listed on the UPA website for some reason. 

Also, my third squat of 155 kg (341 lb) was mistakenly recorded as a missed lift but was given 3 white lights.  You can verify that on my instagram post. [https://www.instagram.com/p/BiIFoJ-g7vN/?taken-by=the_rich_h](url) 

Thanks!

**Comment by sstangl** [comment]
Hi Richard,

The name correction has been fixed, thank you!

Regarding the 3rd squat being recorded as mixed, we can't verify that from an IG post. The question isn't whether the squat looks OK, it's about what the judges saw -- and lifts can be disqualified after-the-fact also. But this is easily solved: please contact the meet director and get them to fix the results on the UPA website. Then let us know, and we'll mirror the change.

**Comment by bobfredc3q** [comment]
Thank you. I figured you'd say something like that about the squat. It's
not too important since my next one will be better anyway.
