### ISSUE TITLE
Update APA for Nicole Park

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#1288]
I haven't update APA for a while, but I should.

She specifically requested (via e-mail):

- [x] http://www.apa-wpa.com/APA/Results/2018Results/GiveStrengthPushPullJanuary27.htm
- [x] http://www.apa-wpa.com/APA/Results/2018Results/2018NortheastUnitedStatesResults.htm
- [x] http://www.apa-wpa.com/APA/Results/2018Results/2018%20CanAm%20Results.htm

**Comment by TrystanOakley** [comment]
Thats cool how you have a checklist made. Didn't know you could do that
