### ISSUE TITLE
Add 2018 VPA Championship

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#1291]
We don't track the VPA currently, but we should. Looks like normal PDF results, not too bad.

From email, via Ngọc Thiện Nguyễn,

Hi OpenPowerlifting,

I would like to contribute official result from my national powerlifting meet that just took place on May 26, 2018.

https://drive.google.com/file/d/1yh-oSlAVOsFTEGOF1t7GZaiA1KJ9RVyU/view?usp=sharing

Event link:
 https://www.facebook.com/events/1748955205188291/permalink/1750728118344333/

Sincerly, 
Thien

**Comment by ngocthien23** [comment]
Thank you for tracking the meet. Please note that some of the lifters had competed in the MPA's. I hope that help you with the data work. 
Please email me if you need a hand!
