### ISSUE TITLE
[suggestion] Lifters - show name once

### ISSUE THREAD

**Issue by KDercksen** [sstangl/openpowerlifting#14]
The lifters page shows for every row the name of the lifter, which seems redundant (unless I'm missing something?). Perhaps it would be nice to just show the name of the lifter once above the table, and remove the `name` column from the table completely.

**Comment by sstangl** [comment]
Maybe. It certainly is redundant, but I like that the table is in roughly the same format as the one on the Rankings page. I'd have to see how it looks before making a switch. I can try out some small prototypes, but I haven't thought of anything that looks good in my head.
