### ISSUE TITLE
check-social-media-csv should make sure each Name actually occurs in the database.

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#144]
People are making more social-media.csv pull requests now, and this would catch typos.

**Comment by TrystanOakley** [comment]
I usually search them up on the site before adding their instagram just so that I can be sure that their name is correct in the database.

**Comment by sstangl** [comment]
The impetus for this was that I personally made a long-standing typo :-)

**Comment by TrystanOakley** [comment]
Oh my bad I thought it was directed at myself.
