### ISSUE TITLE
Add a link to the instagram and facebook page on the site

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#158]
I was thinking it would be beneficial to have a link to the sites instagram and facebook page on the main site somewhere

**Comment by sstangl** [comment]
Oh, yeah, that's probably a good idea. Any ideas for where to put them?

**Comment by TrystanOakley** [comment]
I know some sites have little F and I logos of the facebook and instagram. We could put those up in the top right hand corner to the left of the rankings link? Have it set  up so if you click on it itll take you to our social media? Or we could have another link in that corner that says social media and when you click it it takes you to another page that has links to our instagram and facebook page.

**Comment by sstangl** [comment]
Logos are a great idea. Probably also something on the Contact page.

**Comment by TrystanOakley** [comment]
That would work well

**Comment by sstangl** [comment]
Closed by d324872c5a9bcbbfb8d6c37e2f0623ae62f7311d.
