### ISSUE TITLE
Message Michele Petro when USPA #0872 is Available

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#163]
The lifter Michele Petro requested that we add the UPA meet Summer Showdown that happened June 17th of 2017. I could not find it to add it myself so. Also I currently only know how to add the old archived SPF meets so yeah. Anyways.

**Comment by TrystanOakley** [comment]
lifter-request results

**Comment by TrystanOakley** [comment]
Yeah I don't know how to add labels either. Oh well its 2 am here so goodnight guys.

**Comment by sstangl** [comment]
There's no such meet, as far as I know. We're already 100% complete for the UPA.

The closest thing I could find was the "UPA Summer Showdown 2017", which will take place in September: https://osigym.com/wp-content/uploads/2017/05/UPA-Entry-Form-September-2017.pdf

I think she may be talking about the "USPA Dawg Days of Summer Showdown," sanction ID 872, which did indeed happen on June 17, 2017. Unfortunately, the USPA has not posted those results, so there's nothing we can do about it.

**Comment by sstangl** [comment]
Labels are managed on the right side of this page: there should be a red one there now.

**Comment by TrystanOakley** [comment]
I must have been tired because I just couldn't find how to add it.

**Comment by TrystanOakley** [comment]
Should I message her now ?

**Comment by sstangl** [comment]
The USPA just posted the meet, and it's been added to the site, but there's no lifter named "Michele Petro".

**Comment by sstangl** [comment]
Sure, it should be live in a few moments.

**Comment by TrystanOakley** [comment]
Strange.

**Comment by TrystanOakley** [comment]
It was a UPA meet not uspa. Are they the same?

**Comment by sstangl** [comment]
Uh, there's no such meet in the UPA. I really don't know what she's referring to.

**Comment by TrystanOakley** [comment]
Weeeeird
