### ISSUE TITLE
Some SPF todo meets are empty

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#167]
Example: https://github.com/sstangl/openpowerlifting/blob/master/meet-data/spf-archive/todo/results-0470.csv

**Comment by sstangl** [comment]
Yep. Those results have been lost -- the SPF made a webpage for the meet, but never entered in any data.

Either ignore them, or remove them using "git rm".

Actually, it might be good to just remove all of them at once... then we would have a good idea of how many meets are really remaining. I bet it's not more than 20 meets that are empty, though.

**Comment by sstangl** [comment]
30 meets were empty, I was wrong :-) 254 meets remaining.

**Comment by TrystanOakley** [comment]
If I do one a day we will be good in a about a year! Lol

**Comment by sstangl** [comment]
It would be pretty motivating if the SPF would officially recognize us. Jesse Rodgers said that he loved the site and would contact his webmaster to give us a link... but it looks like never actually did that, and has now forgotten about it.

I don't want to bother him again -- I hope some of the pressure can come from his lifters.

**Comment by TrystanOakley** [comment]
I'm one of his lifters. I know him well. I can talk to him.
