### ISSUE TITLE
Add NASA American Cup in Mt Pleasant Texas, August 19th 2017

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#231]
@Borisdatzar 

Lifter Chris Kearney has requested that this meet be added. NASA hasn't posted it yet, but this is just to track the issue. When it's added, also add his Instagram ya_im_dat_dude.

He said that he lifted in wraps, and "I lift in Pure, Open, and Intermediate divisions."

**Comment by photon-rain** [comment]
http://nasa-sports.com/wp-content/uploads/2017/08/2017-American-CupAugust-19th-20th-2017.pdf
