### ISSUE TITLE
Add 2017 NASA American Cup

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#258]
Meet needs to be added by lifter request -- also send him a follow-up e-mail and add his IG.

> I wanted to submit my meet info my name is Christian Kearney. I weighed in at 142.7 for the NASA American Cup in Mt Pleasant Texas August 19th 2017. Squat 227.5kg 501.55lbs, bench 117.5kg 259.04lbs, deadlift 285kg 628.31lbs total 622.50kg 1372.36lbs  http://nasa-sports.com/wp-content/uploads/2017/08/2017-American-CupAugust-19th-20th-2017.pdf I lift raw with wraps my ig is @ya_im_dat_dude videos are also on there. I lift pure, open, and intermediate divisions age is 28.

**Comment by TrystanOakley** [comment]
I added his instagram

**Comment by sstangl** [comment]
Added by Boris in eef0502d297a5484cc5d8abbb914276da3c9cf2.
