### ISSUE TITLE
SPF ToDo meet 0453 has no lift numbers, just Totals

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#262]
https://github.com/sstangl/openpowerlifting/blob/master/meet-data/spf-archive/todo/results-0453.csv

do I still add this meet just with their totals or do I ignore it all together?

**Comment by sstangl** [comment]
Best to just ignore that for the moment -- there's no way to tell the test suite to not whine about that.

**Comment by TrystanOakley** [comment]
got it.
