### ISSUE TITLE
Lifter Request, add WRPF meet for 2017-04-29

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#266]
Lifter Daniella Tuimatai requested that we add WRPF State Titles meet in Erina NSW Australia where she totalled 585 kg which increases her current rankings on our site. 

I did not add a link to the results because I can not seem to find where the results are on the site. 

Daniella Tuimatai's instagram is @della.powerlifter_doublethick

**Comment by photon-rain** [comment]
http://australia.worldrawpowerlifting.com/competition-rules-results/results/wrpf-new-south-wales-state-titles-2017/
