### ISSUE TITLE
Add Ernie Lilliebridge Jr's 2014 APF Meet

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#331]
APF Holly Jolly Power Bash, 2014-12-06, Aurora, IL.

Lilliebridge totaled 2028 in Wraps.

**Comment by sstangl** [comment]
The meet is not on the APF site and appears to be lost.

**Comment by photon-rain** [comment]
There's video of the meet [here](https://www.2xlpowerlifting.com/live-video-stream/2014-apf-holly-jolly-meet/) if anyone is feeling extremely masochistic one day.

**Comment by sstangl** [comment]
Although the meet isn't on the APF site, it's possible that results are somewhere in the Internet Archive. I haven't gone looking.

**Comment by TrystanOakley** [comment]
Hello,

Unfortunately there were many violations at that event and our  rules and regulations were not followed therefore we had no choice but to decline the sanction.

Kind regards,

Amy Jackson 
WPC/APF Office Manager 
505 Westgate Drive, Aurora, IL 60506 
(630) 896-7309 
www.worldpowerliftingcongress.com

The 2028 total is declined. Closed issue.
