### ISSUE TITLE
PLW reported Larry Williams 2171 total from 2016 being in wraps, not raw

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#338]
http://www.openpowerlifting.org/meet.html?m=spf%2F1628

not sure if he was wrapped or raw but PLW says wrapped

**Comment by sstangl** [comment]
They reported it as Raw here, matching us: http://www.powerliftingwatch.com/records/raw/american

**Comment by TrystanOakley** [comment]
http://www.powerliftingwatch.com/all-time if you go to that link and look at male 242 raw with wraps that total for larry williams is there so

**Comment by sstangl** [comment]
They have an error.

**Comment by TrystanOakley** [comment]
ok
