### ISSUE TITLE
Replace HTML with Tera templates

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#395]
The current `web/templates/` templates should be migrated to Handlebars, for use with the Rocket server.

**Comment by MichaelVessia** [comment]
Do we want to close this, or change it to `tera` templates?

**Comment by sstangl** [comment]
Tera. Handlebars unfortunately had performance issues.

**Comment by sstangl** [comment]
This was done. For the most part. The rest doesn't need an open issue.
