### ISSUE TITLE
Add NZPF results

### ISSUE THREAD

**Issue by photon-rain** [sstangl/openpowerlifting#405]
There currently aren't any local NZPF meet results listed. National NZPF meet results are published on their website and local meet results are published on the corresponding local organisation website. 

NZPF: http://www.nzpowerlifting.co.nz (under results)
Auckland: http://www.sporty.co.nz/aucklandpowerlifting/Results
Waikato/Bay of Plenty: http://www.sporty.co.nz/wbop/Results
Northland: http://www.sporty.co.nz/northlandpowerlifting/NPLA-Records-Results
Otago: http://www.sporty.co.nz/otagoweightlifting/Results/POWERLIFTING-1
Central districts: https://www.facebook.com/CentralDistrictsPowerlifting (Currently no active website, some meet results are posted as images on their facebook page)
Canterbury:  https://www.facebook.com/Canterbury-Powerlifting-Association-108339732541680 (Do not post results on their website, some meet results are posted as images on their facebook page)

**Comment by sstangl** [comment]
Oof, that's extremely difficult. We don't have a good way to automate meet detection for Facebook pages. Also, images take very long to enter -- for mid-sized meets, about an hour.

The absolute best situation for us here would be for someone from the NZPF to organize their data for them, and set up a place where all of the regional meet directors can host their results. It's possible that we could fill that niche -- but, unfortunately, we would have to establish connections with every NZPF meet director, which isn't plausibly going to work. That probably has to come from an NZPF lifter.

Would you be interested in working on this?

**Comment by matt-pearce1** [comment]
Yeah I understand that it probably isn't going to be realistic to enter meet results from Facebook by hand - I was including them mostly just for completeness. I'm based in Australia so probably aren't the person to create a long term solution, however I'd be happy to enter the results that have already been posted if you'd like me to?

**Comment by sstangl** [comment]
Absolutely!

There is some (woefully incomplete) documentation on how to do that here -- https://github.com/sstangl/openpowerlifting/blob/master/docs/results-format.md

You can get a good handle on the `entries.csv` file by looking around the rest of the repository.

If you'd like to start working on that, it's probably a good idea to join the team chat. If you send the project an e-mail, I can send you an invite code.

**Comment by sstangl** [comment]
A lifter on Reddit specifically requested that the following meets be added:

North Island Champs 2016 NZPF https://www.google.co.nz/url?sa=t&source=web&rct=j&url=http://www.sporty.co.nz/asset/downloadasset%3Fid%3D16020619-849b-4152-a6d5-475c062d2c0e&ved=0ahUKEwiMro6-34bYAhVMp5QKHWs7DGkQFghQMAs&usg=AOvVaw18-27oJns0y0Njg-lVViSx

NZPF National Champs 2016 http://www.sporty.co.nz/asset/downloadasset?id=9a2598ff-fa49-49b6-90ba-9255cd066cf2

North Island Champs 2017 NZPF http://www.sporty.co.nz/asset/downloadasset?id=38ebac2e-39d6-4ac4-b7cb-cda5b1adf904

Bledisbro Central Districts Comp 2017 NZPF https://m.facebook.com/CentralDistrictsPowerlifting/photos/a.381240718656751.1073741828.282172675230223/1483146885132790/?type=3&refsrc=http%3A%2F%2Fwww.sporty.co.nz%2Fcentralpowerlifting

**Comment by photon-rain** [comment]
I'll add those meets with the Waikato/BOP meets that I'm working on now.

**Comment by photon-rain** [comment]
All NZ results are done now!
