### ISSUE TITLE
Add Oceania Powerlifting Federation (OceaniaPF) results

### ISSUE THREAD

**Issue by photon-rain** [sstangl/openpowerlifting#406]
OPF is the umbrella organisation for all the Pacific IPF nations, meet results are here:
http://www.oceaniapowerlifting.com/results.htm

**Comment by sstangl** [comment]
Thanks. We track them as "OceaniaPF", but currently only have a single meet of theirs entered, and no probe file.

This is a good first bug, if anyone wants to take it!
