### ISSUE TITLE
Lifter Request to Add a Meet

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#409]
/u/Nizidramaniiyt on reddit requested that we add this meet http://meets.revolutionpowerlifting.com/results/2016-meet-results/peak-performance-power/

**Comment by sstangl** [comment]
It's already in the database. We're complete for the RPS.

Link: http://www.openpowerlifting.org/meet.html?m=rps/1655

**Comment by TrystanOakley** [comment]
My mistake, I did not see it.
