### ISSUE TITLE
Lifter Request to add WRPF meet

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#410]
I have no idea where the WRPF results are and I know they suck at posting them. This is what the lifter sent me.

Name: Edan Davey IG: https://www.instagram.com/edandavey/ Best total: 905 Fed: WRPF Australia Meet: WRPF Downunder Classic 2017 (Sept 02 2017)

He wants that meet added. I asked him to help me find the link to the meet results. He is currently looking. Will update if he finds it.

**Comment by TrystanOakley** [comment]
http://australia.worldrawpowerlifting.com/competition-rules-results/results/2017-wrpf-down-under-classic/

**Comment by TrystanOakley** [comment]
Its a screenshot...he already apologized lol

**Comment by photon-rain** [comment]
Have added this meet.
