### ISSUE TITLE
Add NZPF Raw Record Breakers

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#422]
http://www.sporty.co.nz/asset/downloadasset?id=3884e180-f1a3-41bf-a50c-8c737bf84b96

**Comment by photon-rain** [comment]
Just processed this meet, will upload with the Auckland Powerlifting meets when I'm finished with those.

**Comment by photon-rain** [comment]
This meet and NZPF equipped Nationals are in the database now by the way.

**Comment by sstangl** [comment]
Woo!
