### ISSUE TITLE
Add IPF World Championships for Shane Martin

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#461]
http://www.powerlifting-ipf.com/fileadmin/ipf/data/results/2017/open/detailed_scoresheet_m.htm

Lifter requested we add his 920 kg total meet linked above. His instagram to message once it is added is @smartlifts

**Comment by sstangl** [comment]
This meet was added on November 29th. Shane is already in the database. Perhaps he forgot to select the selector for Single-ply?

http://www.openpowerlifting.org/meet.html?m=ipf%2F1704

**Comment by TrystanOakley** [comment]
Oh I couldn’t find the meet myself. My bad.
