### ISSUE TITLE
Add RPS meet for lifter Nicholas Brooks

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#478]
http://meets.revolutionpowerlifting.com/results/2017-meet-results/2017-rps-texas-merry-gainzmas/

**Comment by photon-rain** [comment]
Added this meet.

**Comment by sstangl** [comment]
This meet was already in the database as `rps/1779`.

The most likely scenario is that Nicholas Brooks competed in sleeves, was marked as Wraps because RPS, sorted by "Raw", didn't see his name, and then assumed we were missing data.

**Comment by TrystanOakley** [comment]
That’s weird, I couldn’t find his meet anywhere. Well thank you. My bad.
Yes he was in sleeves.
