### ISSUE TITLE
data dictionary

### ISSUE THREAD

**Issue by hashtagDoubleM** [sstangl/openpowerlifting#492]
Hi there - I stumbled across the original data on the main website. Is there a data dictionary that provides metadata on the different fields and tables?

**Comment by sstangl** [comment]
What do you mean by metadata? Documentation?

Right now there is no such thing, but the fields should be fairly obvious, for the most part -- there is de-facto documentation for each field in the `tests/` directory, mostly `tests/check-entries-csv`.

There is intended to be documentation here: https://github.com/sstangl/openpowerlifting/blob/master/docs/results-format.md

But it is currently WIP, although not actively being worked on.

**Comment by hashtagDoubleM** [comment]
Yes, that will work. Thanks.
