### ISSUE TITLE
Use Handlebars for table-building

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#494]
It would be nice to use Handlebars to build the tables, instead of having display logic in Rust.

That requires the Handlebars `{{#each}}` performance to be improved.

I filed an issue on the Handlebars side at https://github.com/sunng87/handlebars-rust/issues/195.

**Comment by dginev** [comment]
Hello. I just stumbled into this issue while trying to understand why a table generation of 3,300 rows (~2 MB of HTML) took tens of seconds to generate in my rocket web app.

Thank you for documenting the situation, and would also welcome a performance improvement!

**Comment by sstangl** [comment]
This is actually resolved on our side -- we switched to Tera, which doesn't have the same scaling factor.
