### ISSUE TITLE
Add USPF Mountaineer Open

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#495]
Via email,

>looking and the uspf meets haven't been updated in a while and would like to get my meet on there https://uspfthelegend.com/uploads/2017_WV_USPF_STATE_and_Mountaineer_Open_from_April_1st.pdf

**Comment by camdenmariotti** [comment]
I would add this, but it looks like there are no bodyweights listed, only weight classes.

**Comment by sstangl** [comment]
That's OK -- if no bodyweights are reported, you can omit the `BodyweightKg` column. The compilation step will then assume the pessimal case that they weighed the maximum allowed by the weight class.

**Comment by camdenmariotti** [comment]
done
