### ISSUE TITLE
Add Irish Powerlifting Federation / IrishPF

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#55]
Results are here: http://irishpowerliftingfederation.com/competitions/results/

Unfortunately, it's another federation that uses PDFs, so will be a ton of manual work to import. Fortunately (?), they don't have any results prior to 2015, so there isn't much left.

The meets below look to be a complete list, supplied by Jonathan Gardner:

http://irishpowerliftingfederation.com/wp-content/uploads/2015/06/Inaugural-Results1.pdf
http://irishpowerliftingfederation.com/wp-content/uploads/2015/08/Open-Championships-Results-8th-IrishPF-.pdf
http://irishpowerliftingfederation.com/wp-content/uploads/2016/01/Novice-Open-IPF-Full-Results.pdf
http://irishpowerliftingfederation.com/wp-content/uploads/2016/03/IRISH-POWERLIFTING-FEDERATION-NATIONAL-CHAMPIONSHIP-2016.pdf
http://irishpowerliftingfederation.com/wp-content/uploads/2016/06/boyneside.pdf
https://docs.google.com/spreadsheets/d/1v8Smv7IOV1FpoM9QxtJZCddmVVp_Yosc_lYuGVt9ZxA/pubhtml
https://docs.google.com/spreadsheets/d/1rTs15J4P8LZpezpmbWfjCXEAwG4xWYo51Irnrl3eA_g/pubhtml

So just needs a probe file and a few hours of work.

**Comment by JonnyG1980** [comment]
Hey there, this fed has predominantly moved to google sheets for results -but the older ones above are still on pdf unfortunately. 

I'd love to see these on openpowerlifting.org!

**Comment by sstangl** [comment]
Oh, that's somewhat good news. It looks like they're using "pubhtml" links, and a standardized format, which makes it possible to write an importation script. It also increases the urgency of archiving the federation's data -- anything stored on Google servers is not part of the Web Archive, and may be taken down at any time.

Since you know the federation, I have a question. It looks like equipment is never mentioned. Divisions are marked like "M-O," which for the USAPL means Single-ply. I'm assuming that since raw lifting is much more popular these days, all these lifters are actually raw.

Is there any single-ply competition in this federation, or is it entirely raw? If a lifter competed in single-ply, how can I tell from the results sheet?

**Comment by JonnyG1980** [comment]
It's entirely raw, with (wait for it) 1 equipped single-ply lifter. His results will generally always be at the bottom of the sheets because we don't really know how to say no him. Equipped will have an E class - so M-E in this case. 

M-O would be Male-Open, F would be female. J would be junior (but we rarely classify anyone as anything other than open) M1 etc etc. We also have a classification for guests - G. For those lifters who miss weight and compete anyway.

**Comment by sstangl** [comment]
Thanks. I added a probe file for the federation, so new meets will be automatically detected, and I'll keep being reminded to add these meets.

There is a problem with the website HTML that made writing a probe tricky, because it confused the parser. The results pages sometimes include code that looks like: `<p><a></p><p></a></p>`, which is malformed HTML. Browsers discard the <p>, but the parsing library I'm using is not so smart.

I worked around it for the moment by deleting all the <p> tags.

**Comment by sstangl** [comment]
Hey Jonathan -- all the meets on the website have now been imported. There is some follow-up work for you, if you're interested:

1. The 2015 results webpage implied that there were the meets "Inaugural Championships 2" and "IPF-NIPF Championships 2015", but I couldn't find results from either.

2. It would be very nice to have a link to OpenPowerlifting on the IrishPF website. I would suggest adding a menu item named "Rankings", and linking directly to "http://www.openpowerlifting.org/?fed=IrishPF", which will open to IrishPF-only rankings. Lifters can then see their standing in the IPF/powerlifting as a whole by changing the selectors themselves.

3. Lifter instagrams need tagging. You can do this by editing the file directly (https://github.com/sstangl/openpowerlifting/blob/master/lifter-data/social-media.csv), by opening a new issue, or by sending an email.

4. Scroll through the data and check for anything that seems incorrect.

5. Going forward, it would be extremely helpful to record the date and location (town) of a meet in its results. I had to do some detective work in the Internet Archive to figure out when older meets took place.

This issue is now closed, and the IrishPF is considered fully-supported.
