### ISSUE TITLE
Lifter Request to add SPA meet for Too Chin Siang

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#550]
http://www.powerlifting.com.sg/spa-2017.html requested to be added by @fadzleehairul . 

Too Chin Siang's instagram is trulysuperman

**Comment by sstangl** [comment]
This meet was reported as 9 separate JPG images.

I wonder how I have wronged them.

**Comment by TrystanOakley** [comment]
I am so sorry...
