### ISSUE TITLE
Need to get Mike Womack’s Singly-Ply Record Bench in Database (Lifter Request)

### ISSUE THREAD

**Issue by camdenmariotti** [sstangl/openpowerlifting#553]
Mike Womack notified us on Facebook that he was the actual holder of the single-ply bench record. WABDL is the federation that the lift was made in. Gus Ruthwisch was the meet director.

**Comment by camdenmariotti** [comment]
Contact Mike on Facebook after this is added and before closing issue.

**Comment by photon-rain** [comment]
Results are [here](https://web.archive.org/web/20100217234658/http://www.wabdl.org:80/RESULTS/Southern%20Regional%20BPDL.php)

**Comment by camdenmariotti** [comment]
@photon-rain Wow, thanks for finding that meet! I can't believe you found it! I will work on getting that in **soon**.

**Comment by photon-rain** [comment]
Done!
