### ISSUE TITLE
Add 2017 GPCGB British Championships

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#570]
Via Facebook,

>There's the gpcgb  British championships. Where I went 733kg at 74.3kg bw
> 293kg squat
> 170kg bench
> 270kg deadlift

> https://www.facebook.com/groups/106265919454582/ if you click on info and files you'll be able to find it was held on the 11th nov

**Comment by JoWhiteley** [comment]
This competition is up now.
