### ISSUE TITLE
Searching - multiple matches

### ISSUE THREAD

**Issue by KDercksen** [sstangl/openpowerlifting#6]
Currently the app only gives you the first match of a search query. It would be cool to either filter the list on all matching lifters, or implement some sort of "next match" button that scrolls you to the next positive query match when you click on it. Alternatively, the search button could exhibit this behaviour in some sort of "if the searchfield content didn't change, jump to the next match".

What's your take on this? I'll gladly submit a pull request if I can find the time, but I'd like to know which alternative you'd prefer (if any at all).

**Comment by sstangl** [comment]
Good idea! That's definitely needed.

I think the "next match" behavior would be better. It would also need some sort of UI hint that reactivating the search will have a different effect. We could change the "Search" text to "Next", or put a "Result 3/14" marker somewhere. I'm not sure what would be best. I wonder what people's intuitions are on how to search multiple times. Mine would probably be to hit Enter repeatedly.

Filtering the list would be easy, but a lot of the fun of rankings comes from seeing the small delta between you and the people around you. If we implemented the filter, people's experiences would be to look at the best people at the top, then search for themselves and see only a very limited view. That's not much better than just saying "Your number is XYZ," which is no fun at all. I'd like to keep the presentation always as a huge table, if possible.

**Comment by KDercksen** [comment]
I agree with your points. I'll see if I can get something slapped together tomorrow. My intuition would be to hit enter repeatedly as well, but it would be fairly easy to have it work for both enter and button clicking I suppose. I don't think there needs to be different behaviour in clicking vs entering, that'd only be confusing.

Changing the search text to "Next" is probably the least invasive, since doing something like "Result x/y" is going to change the size of the button, especially if there's a large number of matches.

**Comment by sstangl** [comment]
Resolved by fff079f920cf4c5bc75a2771ca7b81b680c6ee5b.
