### ISSUE TITLE
Lifter Request: Add GPC World Championships 2017

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#615]
https://drive.google.com/file/d/0B5cMCA2voX7udm5BaGNEM1BONG8/view

The lifter is Lil Kimble, @lill_kimble on instagram. She wanted her instagram linked to her name but she isn't in our database because we are missing this meet.

**Comment by TrystanOakley** [comment]
http://www.worldgpc.com/index.php/championships/world-championships/270-gpc-worlds-2017-important-links is the link to the meet on their site 

https://drive.google.com/drive/folders/0B5cMCA2voX7uTHJGTW1ZOUV6emM this is the google drive from the site of all pdfs and excel files. There are a ton. The first google drive link I pasted above is just for the raw Women, not the full meet. Weird formatting.

**Comment by TrystanOakley** [comment]
Please message her on instagram (or tell me to) and add her instagram when it is added.

**Comment by JoWhiteley** [comment]
@TrystanOakley I got the spreadsheet for the whole thing from the facebook group.  added today.

**Comment by sstangl** [comment]
I messaged her.
