### ISSUE TITLE
Lifter Request: Add meet GPA/IPO

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#619]
https://russia-powerlifting.ru/docs/Protokol_Kubka_mira_GPA_IPO_Kubka_Rossii_SAR_i_Chempionata_Rossii_FZhD_Dolgoprudnyi_774_16-17_11_2017.xls

There is the link to the excel file they gave me. The lifter is Lugovoy Alexander. His instagram is lugooovoy. please message him and link his instagram once the meet is added. Thank you

**Comment by photon-rain** [comment]
This meet has already been added.
