### ISSUE TITLE
Add a "UK and Ireland" selector

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#625]
Suggested here: https://www.reddit.com/r/powerlifting/comments/7s6bfy/22_january_2018/dt379wi/

**Comment by JoWhiteley** [comment]
He's right I guess in that there are some competitions that include Irish IPF and NIPF.  The All Ireland is the main one, a team competition between the two.  However, Irish PF affiliate directly to the IPF.  NIPF affilates via British Powerlifting.  They are separate.  I wouldn't ever think to combine the two.

**Comment by sstangl** [comment]
Won't fix after further discussion in that Reddit thread.
