### ISSUE TITLE
Lifter Request: Add WUAP meet for Denise Herber

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#627]
Lifter Denise Herber ( @deniseherber_ ) on instagram asked for her meet to be added and her instagram to be linked. Please message her once this is completed. 

http://wuap-powerlifting.com/images/Results2016/world/Worlds2016_powerliftingRAW.pdf

**Comment by sstangl** [comment]
I messaged Denise on Instagram.
