### ISSUE TITLE
Lifter Request: Add GBPF meet for lifter Claire Vize

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#629]
Please message the lifter at her instagram @builtlikeabarn when the meet has been added and add link her instagram to her name in our database.

http://eastmidspowerlifting.co.uk/?page_id=2 is where the results can be found. Click "East Mids Juniors, Masters and Novices" 2017 tab and the excel file will be downloaded.

**Comment by sstangl** [comment]
For my reference later, I have this meet locally as `jo/EPA-1714`.
