### ISSUE TITLE
Lifter Request: Add GPC Worlds 2017 for lifter Sami Vaskelainen

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#630]
Sami Vaskelainen's instagram is @vaskelainen_powerlifting . Please message once this meet is added and link his instagram to his name. It looks like this is a collection of 20 pdfs so I have no idea how to go about this. 

https://drive.google.com/drive/folders/0B5cMCA2voX7uR29YcDl4cVRXWEk

**Comment by TrystanOakley** [comment]
His individual results look like they are in the PDF listed as 18a

**Comment by JoWhiteley** [comment]
I added this meet today.

**Comment by sstangl** [comment]
I messaged him.
