### ISSUE TITLE
Find and add Beau Moore's 600 lb bench press

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#642]
Beau Moore reportedly benched 600 lbs at age 44 in April of 2010 at the "Beau Moore Classic" sanctioned by the Raw United Federation.

**Comment by photon-rain** [comment]
I think this is it: [link](https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&ved=0ahUKEwjRuMbThZjZAhXEn5QKHQLSBREQFghSMAs&url=https%3A%2F%2Fwww.powerliftingwatch.com%2Ffiles%2Fresults%2FRAW-U-Contest-Results.docx&usg=AOvVaw3KYKNpA_zdOF0-yapx87KY)
