### ISSUE TITLE
Joanne Barnes disambiguation

### ISSUE THREAD

**Issue by JoWhiteley** [sstangl/openpowerlifting#664]
I'm not sure how to process this myself.  I can add "Joanne Barnes,2" but I don;t know how to say which meet belongs to which instance.

One is BP/EPF/IPF the other American/WPC so not too difficult to distinguish

**Comment by sstangl** [comment]
@JoWhiteley If you look at that commit (https://github.com/sstangl/openpowerlifting/commit/14074c69ce7dc26ac4718a2761a2d2d61ae2128d) you can see the changes that this required. It's a little obnoxious, but not too bad!

Eventually we'll probably need a system for making these decisions easier on us, but it's not necessary for the moment.

**Comment by JoWhiteley** [comment]
OK so as well as saying there are two of them, you have to edit each meet to say whether it's 1 or 2.  I get it.  Thanks
