### ISSUE TITLE
Lifter Request: Add CPU meet for princessofpower91 from reddit

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#669]
/u/princessofpower91 from reddit asked for her Canadian Powerlifting Union CPU meet to be added to our to do list. This is her first meet and said she is very excited to see it up on our site. Please message her once it is added. Thank you.

http://www.powerlifting.ca/prov/ontario/2017_vault_barbell_open.php

**Comment by sstangl** [comment]
Huh, I wonder why it's not in the CPU's database?

**Comment by TrystanOakley** [comment]
oh that is weird

**Comment by TrystanOakley** [comment]
Maybe because its a more recent meet? Not sure

**Comment by sstangl** [comment]
I sent her a message.
