### ISSUE TITLE
Result update Madeline Corman

### ISSUE THREAD

**Issue by MACorman** [sstangl/openpowerlifting#672]
The lifts entered for Madeline Corman are outdated. Attached are links verifying the most recent results from the University Powerlifting World Cup.

[http://www.powerlifting-ipf.com/fileadmin/ipf/data/results/2017/university/detailed_scoresheet_w_cup.htm](url)
[http://goodlift.info/lifter.php?lid=11266](url)

**Comment by sstangl** [comment]
Thanks for reporting the missing meet. It should be available here:

http://www.openpowerlifting.org/meet.html?m=ipf/1708

And your personal records should be updated also.
