### ISSUE TITLE
Oceania incomplete

### ISSUE THREAD

**Issue by JoWhiteley** [sstangl/openpowerlifting#745]
Pacific Invitational 2015 missing.
Tbh I've been trying to get my hands on the results for this for a while as it's a missing meet for my region (Tom Martin competed).

**Comment by photon-rain** [comment]
I think the 2015 invitationals are counted as PA meets - haven't been able to find the one that Tom Martin competed at though.

**Comment by JoWhiteley** [comment]
I looked quite hard for it but I've never turned anything up.  It's annoying.

**Comment by photon-rain** [comment]
There seem to be 4 listed - do you know which one he competed in?

**Comment by JoWhiteley** [comment]
it was early December 2015 Oceania Pacific Invitational

**Comment by JoWhiteley** [comment]
It may have been Pacific Invitational 2

**Comment by photon-rain** [comment]
Found it - 2014 Asia/Oceanias.

**Comment by photon-rain** [comment]
Seems they didn't list the results of guest lifters.

**Comment by sstangl** [comment]
Possibly closed by https://github.com/sstangl/openpowerlifting/commit/5d13081d45dfa3af9da8ab70d892ac4ef561f7b0. @photon-rain found the results for Tom Martin, because they were specifically reported on, but the other guest lifters' results are likely lost.
