### ISSUE TITLE
Add GPC-NZ Results for Jamie Whitehead

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#762]
Submitted via e-mail,

Here’s a few of the more recent GPC NZ comps that don’t seem to be on your site. Feel free to trawl through the site and enter them all, or get in contact with any of the team from their contact page for the results in a dif format. 

Thanks,

Jamie

http://gpcpowerlifting.co.nz/wp-content/uploads/2017/12/2017-Push-Pull-Full-Results.xlsx

http://gpcpowerlifting.co.nz/gpc-fitco-bench-only-results-13817/

http://gpcpowerlifting.co.nz/2017-nationals-results/

http://gpcpowerlifting.co.nz/318fitness-kapiti-comp-results/

http://gpcpowerlifting.co.nz/north-island-champs-results-3-lift-and-bench-only/

http://gpcpowerlifting.co.nz/2017-summer-deadlift-results/

Jamie Whitehead

**Comment by sstangl** [comment]
@photon-rain Do you have interest in tracking GPC-NZ results also?

**Comment by photon-rain** [comment]
Yeah I can do that. They don't host that many meets, so it shouldn't be too hard.
