### ISSUE TITLE
Consolidating Meet Results 

### ISSUE THREAD

**Issue by Jadoo-JK** [sstangl/openpowerlifting#763]
Hello, 

I have completed in multiple meets where I was registered under different names. I go by my middle name, Kumar. However, two meets in the past registered me under my first name, Jay. I was wondering if my results could be consolidated under one name, Kumar Jadoo. 

Results under my first name (Jay):
http://www.openpowerlifting.org/lifters.html?q=Jay%20Jadoo

Results under my middle name (Kumar):
http://www.openpowerlifting.org/lifters.html?q=Kumar%20Jadoo

Hoping to have them all under Kumar Jadoo. Please let me know if I need to submit any information for this request to be processed. 

Thank you, 
Kumar

**Comment by sstangl** [comment]
Hi Kumar,

It should be fixed now. It will take a few minutes for the changes to be reflected on the site, and you may have to refresh.

Thank you for the report!
