### ISSUE TITLE
Add 2018 BPU Meets

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#769]
From James Brown via e-mail,

Hi,

Can I please submit Jan/Feb meet results for the BPU fed.

BPU/ABPU UK Results 2018 Jan/Feb:

Alan Collins Cup and South East 2018 Qualifier 
20th & 21st Jan
http://www.britishpowerliftingunion.co.uk/wp-content/uploads/2013/09/Alan-Collins-Cup-2018-Results.docx

North West and Wales 2018 Qualifier 
10th & 11th Feb
http://www.britishpowerliftingunion.co.uk/wp-content/uploads/2013/09/North-West-and-Wales-Qualifier-10-and-11-February-2018-RESULTS.pdf

Thanks

**Comment by JoWhiteley** [comment]
urgh the Alan Collins Cup results are an image of the spreadsheet embedded in a word document.  FFS.

I will try to get spreadsheets or it's a massive data entry job

**Comment by jamesb87** [comment]
@JoWhiteley 
My son is a lifter in this fed and am happy to help conform this data into a more usable format if spreadsheets are not obtainable.
Do you have a standard template for your data imports?

**Comment by JamesBrownUk** [comment]
@JoWhiteley no problem, let me know if you get a response. Would be great if they were able to do this for all results going forward. Thanks

**Comment by JoWhiteley** [comment]
@JamesBrownUk yeah let's give them a week and see how it goes.  I have my hands full looking after British Powerlifting if I'm honest.  I would be happy for you to take on BPU/ABPU results?

**Comment by JoWhiteley** [comment]
I've had a response from BPU and they are looking for the spreadsheets for us.  Fingers crossed.

**Comment by JoWhiteley** [comment]
I just received the spreadsheets. Will upload tomorrow

**Comment by JoWhiteley** [comment]
Added.  This issue can close.
