### ISSUE TITLE
Fix date and location for nzpf/1601

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#779]
While working to remove duplicate NZPF meets, 1601/meet.csv is clearly a copy of 1602/meet.csv. I fixed up the MeetName, but the date and location are probably still wrong.

The PDF did not contain that information.

**Comment by photon-rain** [comment]
Fixed on latest commit

**Comment by photon-rain** [comment]
Thanks for catching this!

**Comment by sstangl** [comment]
Closed by #782.
