### ISSUE TITLE
Lifter Request: Add WPC meet for Alexander Karpenko

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#796]
Чемпионат мира WPC, Кубок Чемпионов мира AWPC 2017  is the name of the meet that can be found here http://www.wpc-wpo.ru/protocols.html . Please message @karpenko181 on instagram once it is added to notify him. He should have been in the "Best of 2017" Top ten for the 181 lb. wrapped class

**Comment by sstangl** [comment]
That name translates as "WPC World Championship" and the second as "AWPC Cup of World Champions".

**Comment by TrystanOakley** [comment]
If you search that link for the name of that meet it is the one that needs to be added
