### ISSUE TITLE
Commonwealth 2017 is not in the database

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#825]
I could not find the meet results on the URL that we have filed but he said that http://www.nipfpowerlifting.co.uk/CompetitionList.php has it listed. At least their results that is, not sure if that is the complete results or not. His instagram is @leemccaff820

**Comment by TrystanOakley** [comment]
Please message him when this is added. Thank you.

**Comment by sstangl** [comment]
CommonwealthPF haven't posted results since 2015. Apparently they exist, but just aren't posted on the website.

**Comment by sstangl** [comment]
The NIPF's version is just for their own lifters.

**Comment by TrystanOakley** [comment]
So do we have the NIPF's version of their commonwealth 2017 meet?

**Comment by sstangl** [comment]
We should not add the NIPF version -- only the full results.

**Comment by photon-rain** [comment]
Aren't the 2017 results on their front page?

**Comment by sstangl** [comment]
It's possible that the probe scripts aren't working right.

**Comment by photon-rain** [comment]
I think Jo filed an issue RE the probe - on mobile otherwise I'd link the number.

**Comment by JoWhiteley** [comment]
The site is stupid.  Latest results aren't on the results page.  They're on the front page.

**Comment by TrystanOakley** [comment]
http://commonwealthpowerlifting.com/2017/powerlifting.htm nice

**Comment by TrystanOakley** [comment]
http://commonwealthpowerlifting.com/2017/powerlifting.htm Here is the link to the meet results

**Comment by TrystanOakley** [comment]
and here is bench only http://commonwealthpowerlifting.com/2017/bench.htm

**Comment by JoWhiteley** [comment]
I thought I could add this quickly but failed results are in as strikethrough.  Will take ages so I will pick it up another day.
