### ISSUE TITLE
Track Rhino Powerlifting Club

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#837]
GPC afilliate Rhino Powerlifting Club can be found here at http://rhinopowerlifting.com/records/ . The lifter who asked about it is @powerlifting_ginger on instagram

**Comment by TrystanOakley** [comment]
I didnt see that you already filed an issue for this. My mistake. This is now closed. I can't close it myself sadly.

**Comment by sstangl** [comment]
Duplicate of #835
