### ISSUE TITLE
Add 2017 IPF Classic Bench Press

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#845]
Submitted by Jason Manenkoff,

http://www.powerlifting-ipf.com/fileadmin/ipf/data/results/2017/classic-benchpress/scoresheet_m.htm (plus the women's sheet).

Our IPF importation script recently grew the ability to parse bench-only IPF meets, so this should be very easy, and there's a non-zero chance @photon-rain has already imported it somewhere.

**Comment by photon-rain** [comment]
I've got this sitting in a branch along with the rest of the IPF results - should be up by the end of the week, I just need to add a couple of meets.
