### ISSUE TITLE
Battle of the Bay 4 Update

### ISSUE THREAD

**Issue by Joe91Coursey** [sstangl/openpowerlifting#851]
file:///C:/Users/TNFlo/AppData/Local/Packages/Microsoft.MicrosoftEdge_8wekyb3d8bbwe/TempState/Downloads/2018%20Battle%20of%20the%20Bay%20IV%20Results.pdf

**Comment by TrystanOakley** [comment]
This is someone on instagram that asked me about getting a meet added and saw the way to add it via github. Since it looks to be a pdf I am getting him to email me the pdf and I will forward it to you @sstangl

**Comment by TrystanOakley** [comment]
Add in USPA Battle of the Bay 4 that can be found here http://uspa.net/competition_results.html @sstangl

**Comment by TrystanOakley** [comment]
The athlete that requested we add it is Joe Coursey @the_traveling_warrior on instagram

**Comment by sstangl** [comment]
USPA posted that meet a few hours ago.
