### ISSUE TITLE
Secondary sort by wilks for SBD

### ISSUE THREAD

**Issue by MichaelVessia** [sstangl/openpowerlifting#854]
Functionality was added where if you sort by Total, it secondarily sorts by Wilks. (#844)

Apply this same logic if you sort by Squat, Bench, or Deadlift.

@sstangl you can assign to me

**Comment by TrystanOakley** [comment]
So is this completed or?

**Comment by MichaelVessia** [comment]
@TrystanOakley It's complete for sorting by total

**Comment by sstangl** [comment]
@TrystanOakley No, this is not completed.
