### ISSUE TITLE
Add a test for Duplicate Meets

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#856]
We do not currently have a way to automatically detect duplicate meets. We should get one in `tests/` to run on checkin. As more people are adding meets, it becomes harder to notice duplicates by yourself.

A meet should probably be considered as a duplicate if the following criteria hold:
1. The `Date` entry in the `meet.csv` file is the same.
2. The `Federation` entry in the `meet.csv` file is the same.
3. For at least one lifter, the same lifter appears in both `entries.csv` files with the same `TotalKg` (and is not `DQ`).

I think that's sufficient and unlikely to have false positives and handles the case where the `MeetName` is different.

This probably could use some more thought before someone goes to implement it.

It's also a little unclear *where* it should be implemented, since it needs to look at all the CSV files at once, and remember which lifters were in which. It probably needs its own thing, which might be too heavyweight.

**Comment by photon-rain** [comment]
I'd avoid doing a federation check - duplicates between IPF and regional affiliates are not that uncommon e.g. for the Arnold's.

**Comment by photon-rain** [comment]
Is there a way of doing this faster than O(N^2)? - if not this is going to be a pain.

**Comment by sstangl** [comment]
`O(n)` hash lookup

**Comment by photon-rain** [comment]
Ah of course.

**Comment by photon-rain** [comment]
This check will be particularly useful for Russian meets, since the results are so spread out.
