### ISSUE TITLE
After sorting by Total, some lifter's Wilks disappears

### ISSUE THREAD

**Issue by MichaelVessia** [sstangl/openpowerlifting#863]
Example:

Load up the main page, sort by Total, and see that Malanichev no longer has a wilks score

**Comment by MichaelVessia** [comment]
Also seems to happen when sorting by other columns

**Comment by MichaelVessia** [comment]
It seems like his weight disappears, and this might drive the wilks value

**Comment by sstangl** [comment]
That's correct behavior. In the case of Malanichev, his best total was at Big Dogs, a special meet that intentionally does not record bodyweight. Because no bodyweight was recorded, they don't have a Wilks. Because they don't have a Wilks, his best-ever meet isn't included in the by-Wilks rankings.

**Comment by MichaelVessia** [comment]
Ok, perfect.  I got worried as I am touching sorting logic :). Closing this issue
