### ISSUE TITLE
Add a test for Unix line endings

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#876]
Sometimes a pull request will make a minor change to a file, but wind up deleting and recreating the entire file due to switching line endings from `\n` to Windows `\r\n`.

We should reject pull requests that contain Windows line endings.

**Comment by MichaelVessia** [comment]
Would setting the project-wide whitespace configuration help?

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

**Comment by sstangl** [comment]
Oh, I had no idea Git could do that! That's even better.
