### ISSUE TITLE
Track WPAU World Powerlifting Alliance Ukraine

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#884]
Lifter @pechkin.p on instagram requested that we start tracking the WPAU federation. I believe this is their site http://wpa-ukraine.com/ but the only sites he linked me to were all powerlifting. He told me that the president of the Macaw in Ukraine would possibly like to help. His name is Kotsaga Vadim and his instagram is @vadymkotsaga

**Comment by sstangl** [comment]
Results are here: http://wpa-ukraine.com/rezultaty/

**Comment by TrystanOakley** [comment]
@sstangl oh thanks for adding that. I was coming here now to add it myself but you beat me to it lol.

**Comment by TrystanOakley** [comment]
Should I message Vady from that fed and see if he would like to help his fed or do you want to?

**Comment by sstangl** [comment]
No, I don't think there's much use in asking for help at the moment.
