### ISSUE TITLE
Add federation config functionality 

### ISSUE THREAD

**Issue by photon-rain** [sstangl/openpowerlifting#887]
It would be useful to have a per federation configuration file for the tests. This would contain parameters such as weight classes, divisions and events contested.

**Comment by sstangl** [comment]
Since it's possible that we may port the testing infrastructure to Rust, JSON would be a good choice.

**Comment by photon-rain** [comment]
The ability to exclude meets from certain tests would also be useful - for example 1989 World games has a men's 90+ class, which triggers a sex- weight-class warning.

**Comment by photon-rain** [comment]
This would also be a good first step towards standardisation of division names for each federation.
