### ISSUE TITLE
Add missing USAPL Arnold meets

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#889]
On Slack,

@sstangl actually looks like you loaded in 4 of the Arnold meets, still missing the The Arnold - Titan Pro Bench Bash (all single-ply): http://usapl.liftingdatabase.com/competitions-view?id=1943, The Arnold - SSP Nutrition Pro Raw Bench (all raw): http://usapl.liftingdatabase.com/competitions-view?id=1942, and The Arnold - Grand Prix by SBD (half and half, denoted in the results file): http://usapl.liftingdatabase.com/competitions-view?id=1941

These meets are not picked up by the `usapl-probe` because the USAPL failed to assign them sanction IDs.

**Comment by emp100k** [comment]
ok I cleaned up these 3 Arnold meets we were missing, what's the easiest way for me to upload them?
