### ISSUE TITLE
Justin Zottl-incorrect entry as raw/sleeves, but competed raw/wraps-275 All Time Canada List

### ISSUE THREAD

**Issue by kushballz69420** [sstangl/openpowerlifting#903]
All time 275 List in sleeves incorrectly has Zottl listed as squatting 804. He competed in wraps, not sleeves. Correct ranking would be Dane Dillon 1, Erik Willis 2, Mike Sinclair 3

**Comment by sstangl** [comment]
The ranking being discussed is "All Canadian Feds", for reference.

**Comment by sstangl** [comment]
The original comment is correct -- Justin Zottl was in wraps.

Video proof is here: https://www.instagram.com/p/BdATzGzHQzj/?taken-by=jzottl

**Comment by sstangl** [comment]
Mohamad Arnaout was also incorrectly reported as being in sleeves from that meet. If you notice any other errors, please let us know. Thank you for reporting!
