### ISSUE TITLE
Add a test for date and federation name being in the MeetName

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#908]
The MeetName in `meet.csv` should not contain year or federation information.

For example, some MeetNames look like: "2015 SPF March Madness". Instead, the MeetName should just be "March Madness", with the rest of the information coming from the other fields.

The beta server tries to combine all the fields helpfully, but it would name the above meet the "2015 SPF 2015 SPF March Madness."

**Comment by MichaelVessia** [comment]
Possibly helpful regex, using SPF as an example:
`\d{4}|\b(?:SPF)\b`
