### ISSUE TITLE
Lifter Request: Add meet for Richard Hawthorne

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#939]
A meet from 2013 is missing for Richard Hawthorne. The meet took place on August 10th and 11th of 2013 at the CAPO National Powerlifting Championships located at the Derwent Ent. Center in Hobart, Tasmania.

The link http://globalpowerliftingalliance.com/results.html is reported as being "dead" for this meet so the way back machine may have to be used to get the results.

**Comment by photon-rain** [comment]
This meet is 13 jpgs :/ https://web.archive.org/web/20160404190038/http://capoaustralianpowerlifting.com.au/index.php/calendar-2/results

**Comment by sstangl** [comment]
Boo, Australia. Boo.
