### ISSUE TITLE
Add 2017 WUAP World Championships

### ISSUE THREAD

**Issue by sstangl** [sstangl/openpowerlifting#958]
Mariša Golob requests that we add this meet -- she says she should have made the top-10 in wraps posting.

Via email,

> My name is Mariša Golob. I compete in 52kg weight class. Last year at WUAP World Championship 2017 I lifted a total of 412,5kg /909,4 lb (the results can be found here 

> http://en.allpowerlifting.com/lifters/SVN/golob-marisa-61386/), which I think is enough for the top 10 results with wraps, but I can’t find my name on the list. Could you maybe add me?

**Comment by sstangl** [comment]
Results are here: http://wuap-powerlifting.com/results/results-2017.

The PDFs come to 207 total pages... most of which are blank or erroneous.

**Comment by photon-rain** [comment]
Ah powerlifting federations and technology, match made in heaven.
