### ISSUE TITLE
Add Aug. 2017 BCPA Lift the Rock

### ISSUE THREAD

**Issue by tollungkrang** [sstangl/openpowerlifting#962]
Hello,

Could you please add competition results for CPU/BCPA meeting Lift The Rock from August 2017. Here are the competition results: http://bc-powerlifting.com/wp-content/uploads/2016/06/2017-Lift-the-Rock-Full-Results-1.pdf

Thank you.

**Comment by sstangl** [comment]
Hi @tollungkrang,

Thanks for the report! It looks like that meet is already in our database. Although, it looks pretty erroneous -- just one lifter. I'll take a look and see what happened. It looks like we may have imported the data at the same time that the CPU was adding it.

http://www.openpowerlifting.org/meet.html?m=cpu/2017-08-06-1e7846a2

**Comment by tollungkrang** [comment]
That is strange. I just noticed I wasn't on there, so I assumed nobody else was. Thanks for the quick response.
