### ISSUE TITLE
Delete a duplicate, Add a new meet

### ISSUE THREAD

**Issue by ChrisLindsay9** [sstangl/openpowerlifting#980]
Thanks for the effort you put into this, it's very much appreciated.  I wanted to report that you have a duplicate meet listed for my profile [ChristopherLindsay](http://www.openpowerlifting.org/lifters.html?q=Christopher%20Lindsay) ... the APF 2016 - 05 - 06 meet is listed twice.  

But I also wanted to see if you can add the AAPF 2016 - 04 - 24 meet?  I posted slightly better numbers at that earlier meet.  Squat: 167.5kg ... Bench: 87.5kg ... Deadlift: 205kg ... Total 450kg ([link](https://worldpowerliftingcongress.com/wpc-results/#1484660793212-58c3007d-64d4))

**Comment by sstangl** [comment]
Hi @ChrisLindsay9, thanks for the report!

The meet is not a duplicate -- you entered two different divisions (once in Open, once in Submasters), so it shows up twice, once per division entered.

We can definitely add the other meet.
