### ISSUE TITLE
Add 2002 MEN'S EUROPEAN POWERLIFTING CHAMPIONSHIPS

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#993]
This meet contains the world record squat done by Andrzej Stanaszek in the EPF (European Powerlifting Federation). This meet can be found by going to http://www.europowerlifting.org/results.html and scrolling down to where it says "archive" at the bottom of the page. Click "archive" then "2002" then "men" and the results will be there.

**Comment by sstangl** [comment]
Note that we added his record as Single-ply and not as Raw (since we don't have any evidence that it was Raw).

**Comment by photon-rain** [comment]
I think @emp100k has pictures of him at this meet? If so, we could check if he's wearing a suit.
